### ISSUE TITLE
TypeScript Error in Middleware

### ISSUE THREAD

**Issue by KingHenne** [reduxjs/redux-thunk#82] opened 2016-07-07 12:46 UTC
The overloading of `Dispatch` by `redux-thunk` breaks middlewares that only handle standard action objects (as apposed to thunks).

Example:

``` ts
import {Action, Dispatch, Middleware, Store} from 'redux';
import {IAppState} from '../reducers';

export const middleware: Middleware = (store: Store<IAppState>) => (next: Dispatch<IAppState>) => (action: Action) => {
  // Do something with the action ...
  next(action);
};
```

The resulting error is:

```
Type '(store: Store<IAppState>) => (next: Dispatch<IAppState>) => (action: Action) => void' is not assignable to type 'Middleware'.
  Type '(next: Dispatch<IAppState>) => (action: Action) => void' is not assignable to type '(next: Dispatch<any>) => Dispatch<any>'.
    Type '(action: Action) => void' is not assignable to type 'Dispatch<any>'.
      Types of parameters 'action' and 'asyncAction' are incompatible.
        Type '(dispatch: Dispatch<any>, getState: () => any, extraArgument: any) => any' is not assignable to type 'Action'.
          Property 'type' is missing in type '(dispatch: Dispatch<any>, getState: () => any, extraArgument: any) => any'.
```

A possible fix to remove the compiler error would be to declare a union type for the Action, i.e. `Action | Redux.ThunkAction<any, IAppState, any>`:

``` ts
export const middleware: Middleware = (store: Store<IAppState>) => (next: Dispatch<IAppState>) => (action: Action | Redux.ThunkAction<any, IAppState, any>) => {
  // Do something with the action ...
  next(action as Action);
};
```

But this is incorrect if your middleware only handles `Action`!

The better solution would be to declare a `Dispatch` interface within the `redux-thunk` module that extends `Redux.Dispatch`. This `Dispatch` could then be used in action creators that return a `ThunkAction`:

``` ts
import {IAppState} from '../reducers';
import {ThunkAction, Dispatch} from 'redux-thunk';

export function thunkedActionCreator(): ThunkAction<void, IAppState, void> {
  return (dispatch: Dispatch<IAppState>, getState: () => IAppState): void => {
    // Do something async and dispatch actions or other thunks ...
  };
}
```

Middlewares on the other hand would use `Redux.Dispatch` (see middleware example above).

**Comment by unional** [comment] 2016-07-19 00:29
I think something is missing here. You do need the `Dispatch<S>` from `redux` to be augmented so that you can call `store.dispatch()` with `thunk`.

**Comment by KingHenne** [comment] 2016-08-02 07:32
@unional Yeah, I didn't really explain this case. You can see in my [PR](https://github.com/gaearon/redux-thunk/pull/83/files#diff-6aaa05299381f4f6e0c957779860c7f7R18) that the `Store` needs to be imported from `redux-thunk` as well in order for this to work:

```ts
import thunk, { Dispatch, ThunkAction, Store } from '../index.d.ts';

declare const store: Store<{foo: string}>;

store.dispatch((dispatch, getState, extraArg) => {
  console.log(extraArg);
});
```

This is of course a very synthetic example. In a real application you would probably have something like a `configureStore` function that would return an instance of the `Store` by `redux-thunk`, e.g.:

```ts
import {applyMiddleware, createStore} from 'redux';
import thunk, {Store} from 'redux-thunk';
import rootReducer, {IAppState} from './rootReducer';

export default function configureStore(initialState: IAppState): Store<IAppState> {
  // You could also configure devtools here and compose with middleware enhancer.
  return createStore(rootReducer, initialState, applyMiddleware(thunk));
}
```

This instance would then be able to `dispatch` thunks.

**Comment by unional** [comment] 2016-08-02 08:05
Well, I think that's a problem. `Store` does not belongs to `redux-thunk`, so we should not export and require user to import `Store` from `redux-thunk`.

Think about it this way: If `redux` and `redux-thunk` are written in TS to begin with, what should have happened? It is an augmentation of a method and should be remain as so.

My two cents, 🌷

**Comment by KingHenne** [comment] 2016-08-02 13:35
@unional, maybe I'm misunderstanding something, but let me try to give you a different perspective.

The `Store` created by `createStore` in the above example is created by the enhancer returned by `applyMiddleWare`, which takes the `Store` instance from the original `createStore` and [replaces](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L32-L35) the `dispatch` method with the composed version of all supplied middlewares. Since `thunk` is the first middleware in the chain, `Store.dispatch` is in fact not the [base implementation](https://github.com/reactjs/redux/blob/master/src/createStore.js#L156-L160) by `redux` but the one by `redux-thunk`. This is expressed by

```ts
export interface Store<S> extends ReduxStore<S> {
  dispatch: Dispatch<S>;
}
```

in my [PR](https://github.com/gaearon/redux-thunk/pull/83/files#diff-b52768974e6bc0faccb7d4b75b162c99R7) and consequently the interface has to be imported from `redux-thunk` and used as the return type of `configureStore` if this is what `configureStore` is doing internally.

**Comment by unional** [comment] 2016-08-02 15:48
I can understand what is your confusion. 

If it is written in typescript, you would do module augmentation. And the `Store` is still imported from `redux` instead of `redux-thunk`. 

If it follows your implementation, then other packages which augment `Dispatch` would need to do the same thing. If user wants to use both `redux-thunk` and `redux-promise`, where should he/she gets the `Store` from?

**Comment by KingHenne** [comment] 2016-08-02 17:15
> Am 02.08.2016 um 17:48 schrieb Homa Wong <notifications@github.com>:
> 
> I can understand what is your confusion.
> 
> If it is written in typescript, you would do module augmentation. And the Store is still imported from redux instead of redux-thunk.
> 
> If it follows your implementation, then other packages which augment Dispatch would need to do the same thing. If user wants to use both redux-thunk and redux-promise, where should he/she gets the Store from?
> 
From whichever is first in the middleware chain. After all the signature of this `dispatch` matches the one that `applyMiddleWare` assigns to the `Store`, doesn't it?

**Comment by unional** [comment] 2016-09-27 18:18
> From whichever is first in the middleware chain.

IMO is not a proper picture. Consider these:

```ts
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import prom from 'redux-promise';
import rootReducer from './reducers';
import { Store } from '???'

// Note: this API requires redux@>=3.1.0
const store: Store = createStore(
  rootReducer,
  applyMiddleware(thunk, prom)
);

const store2: Store = createStore(
  rootReducer,
  applyMiddleware(prom, thunk)
);
```

Where should the `Store` come from? the order of the middleware should have nothing to do with where you get the `Store` from. That's why it is an augmentation.

**Comment by KingHenne** [comment] 2016-09-27 18:47
I see your point. But how can you write a middleware with augmentation then and solve this issue?

**Comment by born2net** [comment] 2016-12-01 08:44
I am using the latest ts and still same issue of:

```
Error:(13, 29) TS2345:Argument of type '(dispatch: any) => void' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: any) => void'.
```
as I am dispatching a thunk

any ideas?

**Comment by unional** [comment] 2016-12-01 19:21
> I see your point. But how can you write a middleware with augmentation then and solve this issue?

With module augmentation (as it is right now), you will get the `Store` from `redux`.

**Comment by unional** [comment] 2016-12-01 19:23
@born2net I think you did not have the typings loaded. It is not distributed in 2.1
You need to get it from github somehow, or use `typings` for this purpose.

**Comment by born2net** [comment] 2016-12-01 19:25
you have a link to the latest / proper definition file I should use?

**Comment by unional** [comment] 2016-12-01 19:37
https://github.com/gaearon/redux-thunk/blob/master/index.d.ts

**Comment by born2net** [comment] 2016-12-01 19:49
tx!!!!!

**Comment by born2net** [comment] 2016-12-01 19:54
unfortunately overriding still results with same error:
```
Error:(13, 29) TS2345:Argument of type '(dispatch: any) => void' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: any) => void'.
```

**Comment by unional** [comment] 2016-12-01 19:55
Can you give a sample of how are you using it?

**Comment by born2net** [comment] 2016-12-01 19:57
sure...
```
export class MyComp {
  constructor(private store: NgRedux<any>, private appStore: AppStore) {
    this.store.dispatch(this.act('222'));
  }

  private act = (i_value): any => {
    return (dispatch) => {
      setTimeout(() => {
        dispatch({type: '555', payload: i_value})
      }, 500)
    }
  }
}
```

**Comment by unional** [comment] 2016-12-01 19:58
How do you get load the typings into your project? Are you using `typings`?

**Comment by born2net** [comment] 2016-12-01 19:58
FYI if I put :any it fixes it... 
```
 private act = (i_value) :any
```

**Comment by born2net** [comment] 2016-12-01 19:59
I did not install any typings and just using my global typings.d.ts (which works great for all my other typings stuff) and pasted your code in... is that wrong?

**Comment by born2net** [comment] 2016-12-01 20:03
even after installing, commenting out and putting updated one, same issue
```
// import * as Redux from "redux";
// import { Middleware } from "redux";

// export as namespace ReduxThunk;
//
// declare const thunk: Middleware & {
// 	withExtraArgument(extraArgument: any): Middleware;
// };
// export default thunk;
//
// declare module 'redux' {
// 	export type ThunkAction<R, S, E> = (dispatch: Dispatch<S>, getState: () => S, extraArgument: E) => R;
//
// 	export interface Dispatch<S> {
// 		<R, E>(asyncAction: ThunkAction<R, S, E>): R;
// 	}
// }



import {Middleware, Dispatch} from "redux";
export type ThunkAction<R, S, E> = (dispatch: Dispatch<S>, getState: () => S,
                                    extraArgument: E) => R;
declare module "redux" {
  export interface Dispatch<S> {
    <R, E>(asyncAction: ThunkAction<R, S, E>): R;
  }
}
declare const thunk: Middleware & {
  withExtraArgument(extraArgument: any): Middleware;
};
export default thunk;
```

**Comment by unional** [comment] 2016-12-01 20:03
Nope, that most likely would not work. Your `typings.d.ts` is probably a global script file while what's in there is a module file, you can wrap this in `declare module `redux-thunk` { ... }` or use `typings to do that for you.

**Comment by born2net** [comment] 2016-12-01 20:03
ok ya tried other way (see prev msg) ... same :/

**Comment by unional** [comment] 2016-12-01 20:05
`typings install github:gaearon/redux-thunk -SD`

Then in your `tsconfig.json` include `typings/index.d.ts` in the `files` section.

**Comment by born2net** [comment] 2016-12-01 20:08
ok I will be back in one hour and will try it ASAP thanks again for the support

**Comment by born2net** [comment] 2016-12-01 21:59
tried to install and got:

```
typings WARN badlocation "github:gaearon/redux-thunk" is mutable and may change, consider specifying a commit hash
typings ERR! message Unable to resolve "github:gaearon/redux-thunk"
typings ERR! caused by https://raw.githubusercontent.com/gaearon/redux-thunk/master/typings.json responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd C:\msweb\msbarcode
typings ERR! system Windows_NT 10.0.14393
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "github:gaearon/redux-thunk" "-SD"
typings ERR! node -v v6.5.0
typings ERR! typings -v 2.0.0
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

**Comment by unional** [comment] 2016-12-01 22:50
Forgot that this doesn't have `typings.json` in the repo.
Do this: `typings install -S redux-thunk=github:gaearon/redux-thunk/index.d.ts`

**Comment by born2net** [comment] 2016-12-01 22:58
still didn't do it 

![image](https://cloud.githubusercontent.com/assets/5090936/20816310/8d2adaba-b7d6-11e6-918e-2bb7b4985a17.png)

**Comment by unional** [comment] 2016-12-01 23:00
Ar, its webstorm. Try to see if it compiles ok or not. It should be. At this point, it is webstorm issue.

**Comment by born2net** [comment] 2016-12-01 23:01
I understand... I appreciate the time...
regards

**Comment by born2net** [comment] 2016-12-01 23:02
not sure if u r into ng2, but if u r:
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by paramsingh88** [comment] 2016-12-27 08:40
@unional @born2net Same Issue! Have tried everything. Please help

**Comment by born2net** [comment] 2016-12-27 14:00
param please follow my setup: https://github.com/born2net/Angular-kitchen-sink

**Comment by aikoven** [comment] 2017-01-18 06:23
Released [v2.1.1](https://github.com/gaearon/redux-thunk/releases/tag/v2.1.1) with TypeScript definitions included.

**Comment by cwharris** [comment] 2017-05-18 20:43
I would expect that Thunk would not overwrite the Redux API without also being backwards compatible. However, this is not the case. Instead, here's a workaround for Middleware type incompatibility.

Found to be working in `typescript@2.2`. Fair warning, There's a possibility this is not intended behavior for the TypeScript compiler.

```TypeScript
import * as Redux from "redux";

const middleware: Redux.Middleware =
  (api: Redux.MiddlewareAPI<void>) => (next: Redux.Dispatch<void>) => <A extends Action>(action: A) => {
    return next(action);
  };
```

**Comment by athornburg** [comment] 2017-08-18 00:18
Hello! I worked with @rodolfo2488 on a fix for this. We believe that this pull request would fix the issue.

**Comment by KingHenne** [comment] 2017-09-04 10:34
I think the original issue can be resolved with improved typings based on https://github.com/reactjs/redux/pull/2563 which hopefully lands soon.

**Closed** 2018-05-25 00:18 UTC
