### ISSUE TITLE
ThunkAction is not assignable to parameter of type 'AnyAction'.

### ISSUE THREAD

**Issue by mendesbarreto** [reduxjs/redux-thunk#333] opened 2022-04-13 19:40 UTC
# Bug Report

## Package name / version

redux-thunk@2.4.1

## Description

I am trying to use a simple method from my store: 

```
store.dispatch(ThunkAction);
```

It is working on run time, but I am receiving an error message on Typescript:

```
TS2345: Argument of type 'ThunkAction<Promise<AuthorizationDto | null>, State, unknown, SetAuthorizationAction>' is not assignable to parameter of type 'AnyAction'.   Property 'type' is missing in type 'ThunkAction<Promise<AuthorizationDto | null>, State, unknown, SetAuthorizationAction>' but required in type 'AnyAction'. 
```

I already tried to import the extend-redux like that:

```
import 'redux-thunk/extend-redux';
```

But the problem is the run time does not find file =S. 

![Screen Shot 2022-04-13 at 3 36 16 PM](https://user-images.githubusercontent.com/2684784/163256747-26b8c209-8d24-452b-bb5a-7efcee617422.png)

I already tried every single solution that's I found on the previous issues, but non of them worked for me.

## Steps to reproduce
- Install the redux-thunk using "npm install"
- Create a ThunkAction
- Call the ```store.dispatch(ThunkAction)``` 
- See typescript Type error

## Expected behavior
No error message from typescript when using  ```store.dispatch(ThunkAction)``` 

## Environment

- OS: macOS Monterey 12.3.1
- Node/npm version: node v16.14.2 / npm 8.5
- Platform: React Native iOS/Android

**Comment by markerikson** [comment] 2022-04-13 21:42
Do you actually have the store configured to use the thunk middleware?

It would really help to see a CodeSandbox or a repo that shows this problem happening.

**Comment by mendesbarreto** [comment] 2022-04-20 00:02
I will create a project that is really simple, you just install the ```redux-thunk@2.4.1``` in a typescript project and try to use ```store.dispatch(ThunkAction);``` from a redux store.

**Comment by markerikson** [comment] 2022-04-20 02:21
@mendesbarreto unfortunately I don't know what the `ThunkAction` variable looks like in this example, or how the middleware was set up, or what TS version you're using, or how TS itself is configured.  So, I really need to see an actual project if at all possible, so I can investigate it myself.

**Comment by yamachu** [comment] 2022-04-20 03:35
@mendesbarreto 
Are you by any chance using react-redux v8?
I have created the following Issue.

https://github.com/reduxjs/react-redux/issues/1911

maybe related
https://github.com/reduxjs/redux-thunk/pull/247

**Comment by Methuselah96** [comment] 2022-04-23 16:48
For me `import 'redux-thunk/extend-redux';` was causing a Webpack error:
```
ERROR in ./source/scripts/app.tsx 5:0-34
Module not found: Error: Can't resolve 'redux-thunk/extend-redux' in 'C:\Users\nbier\Documents\test-app'
```

Ended up using an empty type-import to clue Webpack into realizing I wasn't trying to import a JS module:
```ts
import type {} from 'redux-thunk/extend-redux';
```

**Comment by allicanseenow** [comment] 2022-04-26 00:47
Got the same issue. Would love to have a fix for this.

**Comment by Methuselah96** [comment] 2022-04-26 01:44
@allicanseenow

react-redux v8 was where I was running into the issue as well. Are you importing `redux-thunk/extend-redux` at all? What's the exact error message you're getting?

**Comment by markerikson** [comment] 2022-04-26 01:56
I'll repeat my usual refrain :)

REPROS!  WE NEED REPROS!

We really need actual projects that _show_ the error happening so I can investigate.

**Comment by Methuselah96** [comment] 2022-04-26 04:10
FWIW, I believe the reason this is coming up as an issue with react-redux v8 is because [the v7 `useDispatch()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts#L538-L541) was typed as:

```ts
// NOTE: the first overload below and note above can be removed if redux-thunk typings add an overload for
// the Dispatch function (see also this PR: https://github.com/reduxjs/redux-thunk/pull/247)
export function useDispatch<TDispatch = Dispatch<any>>(): TDispatch;
export function useDispatch<A extends Action = AnyAction>(): Dispatch<A>;
```

The first function overload means you can dispatch literally anything (as a workaround for `redux-thunk`).

But [in v8](https://github.com/reduxjs/react-redux/blob/master/src/hooks/useDispatch.ts#L25-L27) it's now typed as:

```ts
export declare const useDispatch: <AppDispatch extends Dispatch<AnyAction> = Dispatch<AnyAction>>() => AppDispatch;
```

which only allows for `Action` objects.

So this issue isn't "new" it's just been masked by the loose types in the old `react-redux` type definitions.

----

That's just background for why this is coming up now. If you're hitting this error now as a user you should either:

- Use Redux Toolkit and [define typed hooks](https://react-redux.js.org/tutorials/typescript-quick-start#define-typed-hooks) (which will be correctly typed and allow thunk actions)
- If you're using vanilla Redux, most bundlers won't like `import 'redux-thunk/extend-redux'` in a regular TypeScript file because they think you're trying to import JavaScript so you can either:
  - Use `import type {} from 'redux-thunk/extend-redux`
  - Put `/// <reference types="redux-thunk/extend-redux" />` in a `.d.ts` file that's included in your type-checking
  - Put `import 'redux-thunk/extend-redux'` in a `.d.ts` file that's included in your type-checking

**Comment by markerikson** [comment] 2022-04-26 04:19
Huh, good eye! I suppose I accidentally "fixed" this while doing some cleanup on the types :)

**Comment by Methuselah96** [comment] 2022-04-26 04:23
@markerikson [Here](https://github.com/Methuselah96/redux-thunk-dispatch-error/blob/master/src/index.tsx#L10)'s your repro. :)

The line I linked to errors with Webpack because it's trying to import `'redux-thunk/extend-redux'` as a JS module.

**Comment by markerikson** [comment] 2022-04-26 04:26
Heh, thanks :)

So backing up, it sounds like there's two different "issues" going on here:

- `ThunkAction` not dispatching correctly, which we think is due to a change in the v8 `useDispatch` types when the user wasn't actually following our TS setup guidelines
- The separate question of "what is the right way to import the extended global types".  Given that it's a pure types-only file, I think it's safe to assume that it _has_ to be done as `import type` and I just flat-out was wrong with my import instructions.

Is there anything else going on atm beyond those?  Seems like we could consider this resolved if not.

**Comment by allicanseenow** [comment] 2022-04-26 04:37
@markerikson Thanks for looking into this. I am at work but I'll see if I can reproduce the bug locally. The bug occurred to me in a project where I don't use the toolkit but the old redux action/reducer pattern instead.

**Comment by allicanseenow** [comment] 2022-04-26 04:45
@Methuselah96 I was just importing directly `import { ThunkAction } from 'redux-thunk'`. I'll test out the other way to import later as I have recently reverted the react-redux version back to v7.

**Comment by Methuselah96** [comment] 2022-04-26 13:54
@allicanseenow Yeah, an import from `'redux-thunk'` won't extend the Redux types to allow dispatching thunk actions, you have to import `'redux-thunk/extend-redux'` somewhere.

**Comment by Methuselah96** [comment] 2022-04-26 14:09
@markerikson Yeah, that sounds right.

Although on your first point, for vanilla Redux users the TypeScript guide does not mention the need to import `redux-thunk/extend-redux` which could make the most obvious way of typing a `useDispatch` hook with `Dispatch<ThunkAction>` not work. But Redux Toolkit should work fine.

**Comment by markerikson** [comment] 2022-04-26 14:41
In _theory_, our advice of `type AppDispatch = typeof store.dispatch` ought to work even with vanilla `createStore` + `applyMiddleware`, but it's been so long since I've tried it that I'm not 100% sure.

**Comment by Methuselah96** [comment] 2022-04-26 14:47
Yeah if the middleware is the only enhancer it might work, but I don't think composing multiple enhancers with the Redux types works right now without https://github.com/reduxjs/redux/pull/3776 (can we get that merged :)). I haven't tested it out either, so maybe it would work.

**Comment by Methuselah96** [comment] 2022-04-26 16:15
Can confirm that `type AppDispatch = typeof store.dispatch` does not work with vanilla `createStore` + `applyMiddlware`. Here's the [CodeSandbox](https://codesandbox.io/s/holy-currying-5u5dcb?file=/src/index.ts) (not a working app, just checking the types). I didn't get an error in the TypeScript playground, but I believe that's because we haven't removed `@types/react-redux`. I don't think the PR mentioned above would fix this scenario, but I haven't dug into why this doesn't work.

**Comment by markerikson** [comment] 2022-04-26 17:21
Huh, interesting.  We do have a bunch of custom type-level code in `configureStore` to ensure that `dispatch` ends up with the correct types based on the supplied middleware.  I would have thought that `applyMiddleware` would at least do _some_ of that behavior.

**Comment by Methuselah96** [comment] 2022-04-26 18:52
It should, but I don't think people rely on `createStore` doing that in practice since it's been at least partially broken for a long time.

**Comment by blumk** [comment] 2022-06-01 08:53
I'm using Redux Toolkit and upgrading the package version to at least 1.7.0 solved this issue for me.
    
> "@reduxjs/toolkit": "1.7.2",

**Comment by flocbit** [comment] 2022-06-15 10:52
@Methuselah96's solution pointed me in the right direction but since `redux-thunk/src/types.ts` currently has a typescript error which caused my pipelines to fail, I created a redux-thunk.d.ts file:

```typescript

// This is required to fix redux thunk errors introduced with react-redux version 8
import 'redux'

declare module 'redux' {
    /**
     * Overload for bindActionCreators redux function, returns expects responses
     * from thunk actions
     */
    function bindActionCreators<
        ActionCreators extends ActionCreatorsMapObject<any>
    >(
        actionCreators: ActionCreators,
        dispatch: Dispatch
    ): {
        [ActionCreatorName in keyof ActionCreators]: ReturnType<
            ActionCreators[ActionCreatorName]
        > extends ThunkAction<any, any, any, any>
            ? (
                  ...args: Parameters<ActionCreators[ActionCreatorName]>
              ) => ReturnType<ReturnType<ActionCreators[ActionCreatorName]>>
            : ActionCreators[ActionCreatorName]
    }

    /*
     * Overload to add thunk support to Redux's dispatch() function.
     * Useful for react-redux or any other library which could use this type.
     */
    export interface Dispatch<A extends Action = AnyAction> {
        <ReturnType = any, State = any, ExtraThunkArg = any>(
            thunkAction: ThunkAction<ReturnType, State, ExtraThunkArg, A>
        ): ReturnType
    }
}


```

**Comment by sevgeek** [comment] 2022-06-20 11:58
Today I ran into the same problem when I wanted to `dispatch` [initiate action for my API endpoint from `redux-toolkit/rtk-query` library](https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#initiate).

![image](https://user-images.githubusercontent.com/60958933/174596289-30231abe-8d1f-4e9a-8995-e6287a8cced2.png)

@reduxjs/toolkit: 1.8.2
react-redux: 8.0.2

**Comment by Methuselah96** [comment] 2022-06-20 12:47
How are you dispatching it? If you're using `useDispatch` make sure you're using [a typed hook](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks).

**Comment by markerikson** [comment] 2022-06-20 19:30
@sevgeek : can you show your actual store setup code, preferably as a CodeSandbox or Github repo?

**Comment by sevgeek** [comment] 2022-06-21 06:35
> @sevgeek : can you show your actual store setup code, preferably as a CodeSandbox or Github repo?

Yes, sure. I use for configure store very simple reducer, my API slice reducer and additional listener middleware. 
https://codesandbox.io/s/react-redux-toolkit-wbzkgc?file=/src/store/index.ts

I think I found a script to reproduce the TypeScript error.

When I disable the connection of my `[APISlice.reducerPath]`, type `AppDispatch` gets the correct types and allows me to work with `ThunkDispatch`.

![image](https://user-images.githubusercontent.com/60958933/174731006-8a4d6d61-89bb-45eb-ab5f-23555a38151b.png)

When I return connection my `[APISlice.reducerPath]`, `AppDispatch` get a different `type` and then I get type error in my custom hook: https://codesandbox.io/s/react-redux-toolkit-wbzkgc?file=/src/hooks/index.tsx

![image](https://user-images.githubusercontent.com/60958933/174731353-8d58bdfa-c060-4ed8-9e34-2198c112b55c.png)
![image](https://user-images.githubusercontent.com/60958933/174731704-b6780fc9-fc21-44c4-95e7-abae27faa2d0.png)

**Comment by sevgeek** [comment] 2022-06-21 19:40
@markerikson I transferred the pluggable middlewares from `.prepend([])` to `.concat()` and the type error disappeared. 
Thank you very much for your help! 👍🏻

**Comment by allicanseenow** [comment] 2022-10-12 05:14
Forgot to comment. I was able to resolve the issue globally in my personal project by importing 'redux-thunk/extend-redux', as suggested by @Methuselah96 

I created a custom file `custom.d.ts` that has
```
import 'redux-thunk/extend-redux'
```
And I include it in `tsconfig.json`:
```
{
   ...,
   "include" : ["custom.d.ts"],
}
```

**Comment by adriencorbin** [comment] 2022-10-19 14:16
Many Thanks, this workaround works for me too: import 'redux-thunk/extend-redux'

**Comment by vanzinvestor** [comment] 2022-10-21 09:24
`
import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
import { AnyAction } from 'redux';
import { ThunkDispatch } from 'redux-thunk';

const rootReducers = combineReducers();

type AppState = ReturnType<typeof rootReducers>;

type TypedDispatch<T> = ThunkDispatch<T, any, AnyAction>;

export const useAppDispatch = () => useDispatch<TypedDispatch<AppState>>();

export const useAppSelector: TypedUseSelectorHook<AppState> = useSelector;

//USE
const dispatch = useAppDispatch();

const state = useAppSelector((state: AppState) => state.xxx);

`

**Comment by Eversonv4** [comment] 2022-10-27 04:44
> @Methuselah96's solution pointed me in the right direction but since `redux-thunk/src/types.ts` currently has a typescript error which caused my pipelines to fail, I created a redux-thunk.d.ts file:
> 
> ```ts
> // This is required to fix redux thunk errors introduced with react-redux version 8
> import 'redux'
> 
> declare module 'redux' {
>     /**
>      * Overload for bindActionCreators redux function, returns expects responses
>      * from thunk actions
>      */
>     function bindActionCreators<
>         ActionCreators extends ActionCreatorsMapObject<any>
>     >(
>         actionCreators: ActionCreators,
>         dispatch: Dispatch
>     ): {
>         [ActionCreatorName in keyof ActionCreators]: ReturnType<
>             ActionCreators[ActionCreatorName]
>         > extends ThunkAction<any, any, any, any>
>             ? (
>                   ...args: Parameters<ActionCreators[ActionCreatorName]>
>               ) => ReturnType<ReturnType<ActionCreators[ActionCreatorName]>>
>             : ActionCreators[ActionCreatorName]
>     }
> 
>     /*
>      * Overload to add thunk support to Redux's dispatch() function.
>      * Useful for react-redux or any other library which could use this type.
>      */
>     export interface Dispatch<A extends Action = AnyAction> {
>         <ReturnType = any, State = any, ExtraThunkArg = any>(
>             thunkAction: ThunkAction<ReturnType, State, ExtraThunkArg, A>
>         ): ReturnType
>     }
> }
> ```

it worked just fine! thank you very much!

**Comment by bokusunny** [comment] 2023-01-15 08:24
Hi, I could do `store.dispatch(ThunkAction)` by type casting `thunkMiddleWare` before passing to `applyMiddleware` like `applyMiddleware(thunkMiddleWare as ThunkMiddleware<State, Actions>)`. (in case you created store with deprecated `createStore` util).
See: https://codesandbox.io/s/redux-thunk-ts-forked-lzl9d2?file=/src/index.ts

The type of store is:
```ts
// without type casting
const store: Store<State, Action<any>> & {
    dispatch: unknown;
}
store.dispatch(testGetState()); // complained like `Argument of type 'ThunkResult<void>' is not assignable to parameter of type 'Action<any>'.ts(2345)`... :(

// with type casting
const store: Store<State, Action<any>> & {
    dispatch: ThunkDispatch<State, undefined, Actions>;
}
store.dispatch(testGetState()); // working! :)
```

**Comment by markerikson** [comment] 2023-01-15 17:04
@bokusunny : you really shouldn't ever use the TS `Store` type, and definitely not to cast the store setup.

The _right_ answer here is to use Redux Toolkit's `configureStore`, which A) is the recommended way to create a Redux store in the first place, and B) has much better type inference than `createStore` does.

**Comment by pailhead** [comment] 2023-02-03 22:04
How can i make my own magical dispatch that injects stuff:

```
export const useAppDispatch = (): AppDispatch => {
  const { modulePath } = useModuleContext()
  const dispatch = useDispatch()
  const moduleDispatch = useMemo(() => {
    const stableMeta = { modulePath }
    return (action: Parameters<typeof dispatch>[0]) => {
      action.meta = stableMeta
      dispatch(action)
    }
  }, [dispatch, modulePath])
  return moduleDispatch
}
```
It's complaining it can't assign `ThunkAction<...>` to `AnyAction`.

**Comment by markerikson** [comment] 2023-02-03 22:10
@pailhead : a few different issues with that: 

- You should follow our TS guidelines for inferring the type of `dispatch` from the store setup, and then define pre-typed hooks that have that type baked in: https://redux.js.org/tutorials/typescript-quick-start#define-root-state-and-dispatch-types
- You should use that type here: `const dispatch = useAppDispatch()`:
- Instead of `(action: Parameters<typeof dispatch>[0])`, you should type that callback function with the type of `AppDispatch` instead
- You should make sure to include `return`, like `return dispatch(action)`

**Comment by pailhead** [comment] 2023-02-03 22:15
I don't want to use `prepare` looks like, and i want to use `MyAction<T=void> = PayloadAction<T>  & {meta: MyMeta}`, hence the idea to make this kind of a dispatch to complement that :(

**Comment by markerikson** [comment] 2023-02-03 22:18
@pailhead I'm not asking about "why" you're trying to do this - I'm telling you how to fix it :)

**Comment by pailhead** [comment] 2023-02-03 22:21
`Type 'ThunkAction<...> is not assignable to type 'AnyAction`  :(

**Comment by markerikson** [comment] 2023-02-03 22:22
@pailhead I know. _Please_ follow the instructions I gave you to fix that TS error!

**Comment by pailhead** [comment] 2023-02-03 22:25
I'm going around in circles typing as `AppDispatch` seems to leave my action as `any`. `typeof dispatch` is the same as `AppDispatch` so other than returning the last dispatch i don't understand what your instructions are saying that i haven't already done. (Other than the thing where i make `action:any`).

**Comment by markerikson** [comment] 2023-02-03 22:28
@pailhead : 


Assuming you're using Redux Toolkit and following our store setup that I linked,, `AppDispatch` should roughly be something along the lines of `ThunkDispatch & Dispatch<AnyAction>` (going from memory).

Then, you need to _use_ that type for this new "override dispatch" function you're returning:

```ts
  const moduleDispatch = useMemo(() => {
    const stableMeta = { modulePath }
    const mySpecialDispatch: AppDispatch = (action) => {
      action.meta = stableMeta
      return dispatch(action)
    }
  }, [dispatch, modulePath])
```

So:

- Make sure that you have your store setup correct and that hovering over the inferred `AppDispatch` type shows that it includes `ThunkDispatch`.  If this type is wrong, then nothing else will be typed right.
- Use that type as shown above.

**Comment by pailhead** [comment] 2023-02-03 22:31
```
(alias) type WarpDispatch = ThunkDispatch<{
    layout: LayoutState;
}, undefined, AnyAction> & Dispatch<AnyAction>
```
![image](https://user-images.githubusercontent.com/4681282/216723421-4a8652a3-f1f1-40e2-a0f8-6002a61dbf96.png)

**Comment by markerikson** [comment] 2023-02-03 22:33
@pailhead : well, it should :)

Honestly, using this issue thread as a chat support system doesn't work well.

If you're still having issues, please come by the `#redux` channel in the Reactiflux Discord ( https://www.reactiflux.com ), and have a CodeSandbox or a Github repo that shows this happening.

The types and approach I told you _will_ work, but it's also possible that there's something odd about your specific project setup and configuration that we don't know about.

**Closed** 2023-08-19 19:13 UTC
